### ISSUE TITLE
Template setting does not work

### ISSUE THREAD

**Issue by fritzmg** [srhinow/srlayer#4]
Even if you select a custom template (instead of srl_default), it will not be used, because of this small error in [ModuleSRLayer](https://github.com/srhinow/srlayer/blob/master/ModuleSRLayer.php#L59):
```php
if($this->srl_template != '') $strTemplate = $this->srl_template;
```
It should instead say:
```php
if($this->srl_template != '') $this->strTemplate = $this->srl_template;
```

**Comment by srhinow** [comment]
thanks,
is fixed in the newest version
