### ISSUE TITLE
FR: Prozentuale Maße

### ISSUE THREAD

**Issue by design23** [srhinow/srlayer#5]
Hi, 
erstmal danke für die Erweiterung. Ist sehr schön und bequem einzusetzen.
Eine kleine Sache empfinde ich aber als unpraktisch: Feste Pixelwerte für die Größendefinitionen sind in Hinblick auf responsive Design eher unvorteilhaft. Ist es möglich, hier auch %-Werte zu verwenden, so wie es bsp. bei colorbox auch möglich ist?

**Comment by srhinow** [comment]
Hi,
ich habe in der neuen Version diverse Vorgaben die per Javascript gesetzt wurden raus genommen. Die müssen zukünftig per CSS gesetzt werden. Dazu gehören die Breite, Höhe, Position und die Transparenzen.
Ich denke, so kann wesentlich flexibler auf den Einsatz reagiert werden.
