### ISSUE TITLE
Why is there a typolight path in ModuleSRLayer.php

### ISSUE THREAD

**Issue by Aybee** [srhinow/srlayer#6]
Isn't this causing problems ever?
`typolight/main.php`
https://github.com/srhinow/srlayer/blob/master/ModuleSRLayer.php#L55

**Comment by Aybee** [comment]
Ups forgot to say. Just tried to use 3.0.1 on Contao 3.5.12 and it seems to work as expected. Maybe you can raise the requirement to C 3.5.12 soon.

**Comment by srhinow** [comment]
thanks
is now fixed.

**Comment by srhinow** [comment]
and is tested and developed with contao 3.5.12
