### ISSUE TITLE
Felder Overlay-ID, Layer-ID, Schließen-Button-ID, Schließen-Link-Klasse lassen sich im BE nicht editieren

### ISSUE THREAD

**Issue by joehi** [srhinow/srlayer#8]
Im Backend lassen sich unter "Javascript-Einstellungen bearbeiten" die Felder "Overlay-ID", "Layer-ID", "Schließen-Button-ID" sowie "Schließen-Link-Klasse" nicht editieren. Auch die Hilfetexte werden nicht komplett angezeigt bei Mous-Hover.

Das \<h3\> von "Einblend-Geschwindigkeit" (ctrl_srl_set_duration) scheint hier die obigen Felder mit seinem oberen Abstand zu überdecken.

Es fehlt hier beim "<div class="widget" von "Einblend-Geschwindigkeit" (ctrl_srl_set_duration) das "w50", korrekt wäre: "<div class="w50 widget".

Ich mache dazu einen Pull-Request mit dem Fix in der srlayer/dca/tl_module.php

**Comment by srhinow** [comment]
Danke für die beiden Pull-Requests.

Kannst du evtl noch hier rein schreiben in welcher Contao-Version du dies einsetzt / der Fehler aufgetreten ist?

**Comment by joehi** [comment]
Ich habe es unter Contao 4.7.4 getestet.
